=== folio-org/mod-calendar/ramls/schemas/Opening.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Opening",
  "type": "object",
  "description": "Descriptor an opening period.",
  "properties": {
    "id": {
      "type": "string",
      "description": "Period's internal id."
    },
    "servicePointId": {
      "type": "string",
      "description": "Service point ID."
    },
    "name": {
      "type": "string",
      "description": "Name of the period"
    },
    "startDate": {
      "type": "string",
      "format": "date-time",
      "description": "Start date of the period."
    },
    "endDate": {
      "type": "string",
      "format": "date-time",
      "description": "End date of the period."
    },
    "openingDays": {
      "type": "array",
      "description": "List opening hours within the period.",
      "items": {
        "type": "object",
        "$ref": "OpeningDayIncludeWeekdays.json"
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "startDate"
  ]
}

=== folio-org/mod-calendar/ramls/examples/opening_get.json
{
  "id": "ha9927e8-5f79-498e-94ea-8b5b474795c8",
  "servicePointId": "1",
  "name": "test2",
  "startDate": "2018-09-01T00:00:00.000+0000",
  "endDate": "2018-10-01T00:00:00.000+0000",
  "openingDays": [
    {
      "weekdays": {
        "day": "THURSDAY"
      },
      "openingDay": {
        "openingHour": [
          {
            "startTime": "09:00",
            "endTime": "12:00"
          },
          {
            "startTime": "13:00",
            "endTime": "17:00"
          }
        ],
        "allDay": false,
        "open": true,
        "exceptional": false
      }
    }
  ]
}

=== folio-org/mod-calendar/scripts/test-calendars/normal-2021-12-05-through-2021-12-31.json
{
  "id": "33333333-3333-3333-3333-333333333333",
  "servicePointId": "3a40852d-49fd-4df2-a1f9-6e2641a6e91f",
  "name": "December 5 through 31",
  "startDate": "2021-12-05",
  "endDate": "2021-12-31",
  "openingDays": [
    {
      "weekdays": {
        "day": "MONDAY"
      },
      "openingDay": {
        "openingHour": [
          {
            "startTime": "07:30",
            "endTime": "17:30"
          }
        ],
        "allDay": false,
        "open": true
      }
    },
    {
      "weekdays": {
        "day": "TUESDAY"
      },
      "openingDay": {
        "openingHour": [
          {
            "startTime": "07:30",
            "endTime": "17:30"
          }
        ],
        "allDay": false,
        "open": true
      }
    },
    {
      "weekdays": {
        "day": "WEDNESDAY"
      },
      "openingDay": {
        "openingHour": [
          {
            "startTime": "00:00",
            "endTime": "23:59"
          }
        ],
        "allDay": true,
        "open": true
      }
    },
    {
      "weekdays": {
        "day": "THURSDAY"
      },
      "openingDay": {
        "openingHour": [
          {
            "startTime": "07:30",
            "endTime": "17:30"
          }
        ],
        "allDay": false,
        "open": true
      }
    },
    {
      "weekdays": {
        "day": "FRIDAY"
      },
      "openingDay": {
        "openingHour": [
          {
            "startTime": "07:30",
            "endTime": "17:30"
          }
        ],
        "allDay": false,
        "open": true
      }
    },
    {
      "weekdays": {
        "day": "SATURDAY"
      },
      "openingDay": {
        "openingHour": [
          {
            "startTime": "07:00",
            "endTime": "12:00"
          },
          {
            "startTime": "13:30",
            "endTime": "20:00"
          }
        ],
        "allDay": false,
        "open": true
      }
    }
  ]
}

=== folio-org/mod-calendar/scripts/test-calendars/exception-final-opening.json
{
  "id": "11111111-1111-1111-1111-111111111111",
  "servicePointId": "3a40852d-49fd-4df2-a1f9-6e2641a6e91f",
  "name": "Finals Extra Opening",
  "startDate": "2021-12-11",
  "endDate": "2021-12-17",
  "openingDays": [
    {
      "openingDay": {
        "openingHour": [
          {
            "startTime": "02:00",
            "endTime": "23:00"
          }
        ],
        "open": true
      }
    }
  ]
}

=== folio-org/mod-calendar/scripts/test-calendars/exception-christmas-closure.json
{
  "id": "00000000-0000-0000-0000-000000000000",
  "servicePointId": "3a40852d-49fd-4df2-a1f9-6e2641a6e91f",
  "name": "Christmas Closure",
  "startDate": "2021-12-24",
  "endDate": "2021-12-25",
  "openingDays": [
    {
      "openingDay": {
        "openingHour": [
          {
            "startTime": "00:00",
            "endTime": "23:59"
          }
        ],
        "allDay": true,
        "open": false
      }
    }
  ]
}
